# Generated by Django 4.1.4 on 2022-12-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_locaux_visiteur_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiteur',
            name='equipe',
        ),
        migrations.AddField(
            model_name='match',
            name='score_locaux',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_visiteurs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='locaux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='polls.equipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='visiteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteurs', to='polls.equipe'),
        ),
        migrations.DeleteModel(
            name='Locaux',
        ),
        migrations.DeleteModel(
            name='Visiteur',
        ),
    ]
