# Generated by Django 4.1.4 on 2022-12-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_visiteurs', models.IntegerField(default=0)),
                ('score_locaux', models.IntegerField(default=0)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ligue')),
                ('locaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='polls.equipe')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteurs', to='polls.equipe')),
            ],
        ),
    ]
