# Generated by Django 4.1.4 on 2022-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_match_id_match_id_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id_match',
        ),
        migrations.AddField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
