# Generated by Django 4.1.4 on 2022-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=20),
        ),
    ]
