# Generated by Django 4.1.4 on 2022-12-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_equipe_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ligue')),
                ('locaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.locaux')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.visiteur')),
            ],
        ),
    ]
