# Generated by Django 4.1.4 on 2022-12-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_match_point_locaux_match_point_visteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='point_locaux',
        ),
        migrations.RemoveField(
            model_name='match',
            name='point_visteur',
        ),
    ]
