# Generated by Django 4.1.4 on 2022-12-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_match_point_locaux_remove_match_point_visteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_locaux',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_visiteurs',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
