# Generated by Django 4.1.4 on 2022-12-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_match_score_locaux_alter_match_score_visiteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default='1999-10-17'),
            preserve_default=False,
        ),
    ]
